replicaCount: 1
image:
  repository: "springbootrest"
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: springbootrest.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []