apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: "myuser"
  SPRING_DATASOURCE_PASSWORD: "mypassword"
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/springbootrest"
  SPRING_DATASOURCE_WRITER_URL: "jdbc:mysql://mysql:3306/springbootrest"